name: Manual Publish
run-name: Deploy ${{ github.event.inputs.version }} to ${{ github.event.inputs.target }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      target:
        description: "选择发版目标"
        required: true
        default: "backend"
        type: choice
        options:
          - backend
          - frontend
          - all
      version:
        description: "版本号 (如 v1.0.0)"
        required: true

jobs:
  # --- 后端构建任务 ---
  build-backend:
    if: ${{ github.event.inputs.target == 'backend' || github.event.inputs.target == 'all' }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: 登录 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 打包 & 推送后端镜像
        uses: docker/build-push-action@v5
        with:
          context: ./backend # 这里的路径必须对应你的子目录
          push: true
          tags: |
            ghcr.io/dancingcodes/filehub-backend:${{ github.event.inputs.version }}
            ghcr.io/dancingcodes/filehub-backend:latest

      - name: 远程部署
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/filehub
            docker compose pull backend
            docker compose up -d backend

  # --- 前端构建任务 ---
  build-frontend:
    if: ${{ github.event.inputs.target == 'frontend' || github.event.inputs.target == 'all' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 打包
        run: |
          cd frontend
          npm install
          npm run build
          tar -czf dist.tar.gz dist/

      - name: 发送到服务器
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/dist.tar.gz"
          target: "/opt/filehub/frontend"
          strip_components: 1

      - name: 远程部署与版本留存
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/filehub/frontend
            mkdir -p backups
            cp dist.tar.gz backups/frontend-${{ github.event.inputs.version }}.tar.gz
            tar -xzf dist.tar.gz
            rm dist.tar.gz